// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuPX106-RRIfA7mzNy3hJQ-oJvL9q8Y50',
    appId: '1:355406099603:web:545c982bffad0e69d44966',
    messagingSenderId: '355406099603',
    projectId: 'lingowave-b1d94',
    authDomain: 'lingowave-b1d94.firebaseapp.com',
    storageBucket: 'lingowave-b1d94.firebasestorage.app',
    measurementId: 'G-G4M6DS7RDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4VCa4LqFqFFX3zRcET7Rg_XPl1Ydfik',
    appId: '1:355406099603:android:419e67ce68726200d44966',
    messagingSenderId: '355406099603',
    projectId: 'lingowave-b1d94',
    storageBucket: 'lingowave-b1d94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiFPR0p0dD2c88zl-Liuxwy4_e-ZaFjp8',
    appId: '1:355406099603:ios:b2a2cd226dd94ecad44966',
    messagingSenderId: '355406099603',
    projectId: 'lingowave-b1d94',
    storageBucket: 'lingowave-b1d94.firebasestorage.app',
    androidClientId: '355406099603-vh5fr32no57993daf7ukj0q3eauhbh8h.apps.googleusercontent.com',
    iosClientId: '355406099603-nrl9u5edv123u8d3v05i6aj87n5iefiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.lingowave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiFPR0p0dD2c88zl-Liuxwy4_e-ZaFjp8',
    appId: '1:355406099603:ios:b2a2cd226dd94ecad44966',
    messagingSenderId: '355406099603',
    projectId: 'lingowave-b1d94',
    storageBucket: 'lingowave-b1d94.firebasestorage.app',
    androidClientId: '355406099603-vh5fr32no57993daf7ukj0q3eauhbh8h.apps.googleusercontent.com',
    iosClientId: '355406099603-nrl9u5edv123u8d3v05i6aj87n5iefiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.lingowave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuPX106-RRIfA7mzNy3hJQ-oJvL9q8Y50',
    appId: '1:355406099603:web:94e872ec931965a8d44966',
    messagingSenderId: '355406099603',
    projectId: 'lingowave-b1d94',
    authDomain: 'lingowave-b1d94.firebaseapp.com',
    storageBucket: 'lingowave-b1d94.firebasestorage.app',
    measurementId: 'G-R9GNR7MZWQ',
  );
}
